CREATE OR REPLACE FUNCTION AUTHORS_LIST_FUNC(TEMP_DOC_ID IN NUMBER)
RETURN VARCHAR2 IS

	TEMP_AUTHORS_LIST VARCHAR2(500);
	
BEGIN
	TEMP_AUTHORS_LIST := '';
	FOR AUTHOR IN (
		SELECT (INITCAP(P1.FIRST_NAME) || ' ' || INITCAP(P1.LAST_NAME) ) NAME
		FROM PERSON P1, TEMP_WRITTEN_BY W1 
		WHERE W1.DOC_ID = TEMP_DOC_ID AND W1.RESEARCHER_ID = P1.PERSON_ID)
	LOOP
		TEMP_AUTHORS_LIST := TEMP_AUTHORS_LIST || AUTHOR.NAME || ', ';
	END LOOP;
	
	TEMP_AUTHORS_LIST := SUBSTR(TEMP_AUTHORS_LIST, 1, LENGTH(TEMP_AUTHORS_LIST) - 2);
		
	RETURN TEMP_AUTHORS_LIST;
END;
/


--   Handle affiliation and aff_with while registering as a researcher

CREATE OR REPLACE PROCEDURE AFF_HANDLE(ID_PERSON IN NUMBER, INST IN VARCHAR2, DESIG IN VARCHAR2) IS
	INST_COUNT NUMBER;
	AFF_ID NUMBER;
	EXIST_COUNT NUMBER;
BEGIN
	SELECT COUNT(*) INTO INST_COUNT
	FROM AFFILIATION 
	WHERE LOWER(NAME) LIKE LOWER(INST);
	
	DBMS_OUTPUT.PUT_LINE('GOT THE COUNT : ' || INST_COUNT);
	
	IF INST_COUNT = 0 THEN
		INSERT INTO AFFILIATION (AFFILIATION_ID, NAME) VALUES(AFFILIATION_ID_GENERATOR.NEXTVAL, INST);
		COMMIT;
		AFF_ID := AFFILIATION_ID_GENERATOR.CURRVAL;
	ELSE 
		SELECT AFFILIATION_ID INTO AFF_ID FROM AFFILIATION WHERE LOWER(NAME) LIKE LOWER(INST);
	END IF;
	
	SELECT COUNT(PERSON_ID) INTO EXIST_COUNT FROM AFF_WITH WHERE PERSON_ID = ID_PERSON;
	
	IF EXIST_COUNT > 0 THEN
		UPDATE AFF_WITH SET AFFILIATION_ID = AFF_ID, DESIGNATION = DESIG WHERE PERSON_ID = ID_PERSON;
	ELSE
		INSERT INTO AFF_WITH VALUES(ID_PERSON, AFF_ID, DESIG);
	END IF;

	COMMIT;

END;
/



-- full name of a person given first_and_last name
CREATE OR REPLACE FUNCTION
get_full_name (first_name IN VARCHAR2, last_name IN VARCHAR2)
RETURN VARCHAR2 IS
	name VARCHAR2(500);
BEGIN
	IF last_name IS NULL THEN
		name := first_name;
	ELSE
		name := first_name || ' ' || last_name;
	END IF;
	
	RETURN name;
END ;
/

/*
---------- TESTS -----------
SELECT * FROM user_errors;
SELECT get_full_name(FIRST_NAME, LAST_NAME) AS full_name
FROM PERSON;
*/

-- full name given person_id
CREATE OR REPLACE FUNCTION
get_full_name_of_person (per_id INTEGER)
RETURN VARCHAR2 IS
	full_name VARCHAR2(500);
BEGIN
	SELECT get_full_name(per.FIRST_NAME, per.LAST_NAME) INTO full_name
	FROM PERSON per
	WHERE per.PERSON_ID = per_id;
	
	RETURN full_name;
END ;
/

/* 
--------------- TESTS ------------------
SELECT get_full_name_of_person(1000)
FROM dual;
*/


CREATE OR REPLACE FUNCTION
days_from_now (given_time DATE)
RETURN INTEGER IS
BEGIN
	RETURN TRUNC(SYSDATE) - TRUNC(given_time);
END ;
/


/* 
--------------- TESTS ------------------
SELECT days_from_now(SYSDATE - 10)
FROM dual;
*/