--NOTI ON CITE TRIGGER:

CREATE OR REPLACE TRIGGER NOTI_ON_CITE
AFTER INSERT
ON CITES
FOR EACH ROW
DECLARE
    TEMP_DOC_ID NUMBER;
    TEMP_TIME DATE;
    TEMP_DESCRIPTION VARCHAR2(1000);

    TEMP_CITER_ID NUMBER;
    CITER_TITLE VARCHAR2(500);
    CITER_URL VARCHAR2(800);
    CITER_AUTHORS VARCHAR2(500);
BEGIN
    TEMP_DOC_ID := :NEW.CITEE_ID;
    TEMP_CITER_ID := :NEW.CITER_ID;
    TEMP_TIME := :NEW.CITE_TIME;
	
	CITER_AUTHORS := '';
	FOR AUTHOR IN (
		SELECT (INITCAP(P1.FIRST_NAME) || ' ' || INITCAP(P1.LAST_NAME) ) NAME
		FROM PERSON P1, WRITTEN_BY W1 
		WHERE W1.DOC_ID = TEMP_CITER_ID AND W1.RESEARCHER_ID = P1.PERSON_ID)
	LOOP
		CITER_AUTHORS := CITER_AUTHORS || AUTHOR.NAME || ', ';
	END LOOP;
	
	CITER_AUTHORS := SUBSTR(CITER_AUTHORS, 1, LENGTH(CITER_AUTHORS) - 2);
	DBMS_OUTPUT.PUT_LINE(CITER_AUTHORS);
	
    FOR R IN (SELECT PER.PERSON_ID FROM WRITTEN_BY WBY, PERSON PER
        WHERE WBY.DOC_ID = TEMP_DOC_ID AND PER.PERSON_ID = WBY.RESEARCHER_ID)
    LOOP

        SELECT TITLE, URL INTO CITER_TITLE, CITER_URL FROM DOCUMENT WHERE DOC_ID = TEMP_CITER_ID;
        TEMP_DESCRIPTION := 'You got new citation from "' || INITCAP(CITER_TITLE) || '" Authored by ' || CITER_AUTHORS; 

        INSERT INTO NOTIFICATION 
        VALUES(NOTIFICATION_ID_GENERATOR.NEXTVAL, R.PERSON_ID, TEMP_DOC_ID, 'cite', TEMP_TIME, TEMP_DESCRIPTION);
    END LOOP;
 	
END;
/

CREATE OR REPLACE TRIGGER NOTI_ON_REPLY
AFTER INSERT
ON REPLY
FOR EACH ROW
DECLARE
	-- NUMBER DATE VARCHAR2(1000);
	person_id_  NUMBER;
	doc_id_     NUMBER;
	noti_type_  VARCHAR2(500) := 'on_reply_on_comment';
	event_time_ DATE;
	desription_ VARCHAR2(500);
	post_id_    NUMBER;
	disc_id_    NUMBER;
	noti_id_    NUMBER := NOTIFICATION_ID_GENERATOR.NEXTVAL;
	replier_name_ VARCHAR2(500);
BEGIN
	post_id_    := :NEW.POST_ID;
	disc_id_    := :NEW.DISCUSSION_ID;

	
	SELECT 
		disc.DOC_ID, post.PERSON_ID 
			INTO doc_id_, person_id_
	FROM DISCUSSION disc
	INNER JOIN POSTS post 
		ON (post.POST_ID = disc.POST_ID AND disc.POST_ID = disc_id_);
	
	SELECT
		CAST(post.TIMESTAMP_ AS DATE), GET_FULL_NAME_OF_PERSON(per.PERSON_ID)
			INTO event_time_, replier_name_
-- 	FROM REPLY rep
	FROM POSTS post 
	INNER JOIN PERSON per ON(per.PERSON_ID = post.PERSON_ID)
	WHERE (post.POST_ID = post_id_);
	
-- 	event_time_ := CAST(event_time_ AS DATE);
	desription_ := replier_name_ || ' ' || 'replied to your post';
	INSERT INTO NOTIFICATION 
	VALUES(noti_id_, person_id_, doc_id_, noti_type_, event_time_ , desription_);
	
END;
/


CREATE OR REPLACE TRIGGER NOTI_ON_COMMENT
AFTER INSERT
ON DISCUSSION
FOR EACH ROW
DECLARE
	-- NUMBER DATE VARCHAR2(1000);
	doc_id_     NUMBER;
	noti_type_  VARCHAR2(500) := 'on_discussion_on_doc';
	event_time_ DATE;
	desription_ VARCHAR2(500);
	post_id_    NUMBER;
	discusser_name_  VARCHAR2(500);
	
BEGIN
	post_id_ := :NEW.POST_ID;
	doc_id_  := :NEW.DOC_ID;	
	SELECT
		CAST(post.TIMESTAMP_ AS DATE), GET_FULL_NAME_OF_PERSON(per.PERSON_ID)
			INTO event_time_, discusser_name_
	FROM POSTS post
	INNER JOIN PERSON per ON(per.PERSON_ID = post.PERSON_ID)
	WHERE (post.POST_ID = post_id_);
	
	desription_ := discusser_name_ || ' ' || 'commented on your paper';
	
	FOR cur IN (SELECT DISTINCT wby.RESEARCHER_ID AS res_id
				FROM DOCUMENT doc
                INNER JOIN WRITTEN_BY wby ON(wby.DOC_ID = doc.DOC_ID and doc.DOC_ID = doc_id_)
	) LOOP
		INSERT INTO NOTIFICATION
		VALUES(NOTIFICATION_ID_GENERATOR.NEXTVAL, cur.res_id, doc_id_, noti_type_, event_time_ , desription_);
	
	END LOOP;	
END;
/
