-- citation count of document
CREATE OR REPLACE VIEW DOC_CITATION_COUNT(doc_id, num) AS
	SELECT 
		doc.DOC_ID,
		(SELECT COUNT(*) FROM CITES c WHERE c.CITEE_ID = doc.DOC_ID) num
	FROM DOCUMENT doc
	ORDER BY doc.DOC_ID;


-- total citations of the RESEARCHER
CREATE OR REPLACE VIEW RESEARCHER_CITATION_COUNT(researcher_ID, num) AS
SELECT res.PERSON_ID, SUM(cit.num)
FROM RESEARCHER res
	INNER JOIN WRITTEN_BY wby ON (res.PERSON_ID = wby.RESEARCHER_ID)
	INNER JOIN DOCUMENT doc ON (wby.doc_ID = doc.DOC_ID)
	INNER JOIN DOC_CITATION_COUNT cit ON (doc.DOC_ID = cit.DOC_ID)
GROUP BY res.PERSON_ID;


-- https://leetcode.com/problems/h-index/

CREATE OR REPLACE VIEW PUBLICATIONS_DOC_CITATIONS(PUB_ID, num) AS

SELECT 
	pby.PUB_ID, 
	
-- 	SUM(dcnt.NUM) AS NUM
-- 	doc.DOC_ID,
	dcnt.NUM AS NUM
FROM DOCUMENT doc
	INNER JOIN PUBLISHED_BY pby ON(doc.DOC_ID = pby.DOC_ID)
	INNER JOIN DOC_CITATION_COUNT dcnt ON(doc.DOC_ID = dcnt.DOC_ID)
-- GROUP BY pby.PUB_ID
ORDER BY pby.PUB_ID ASC, NUM DESC;