--person_id primary key generator sequence:

-- drop sequence person_id_generator;

CREATE SEQUENCE person_id_generator
INCREMENT BY 1
START WITH 1300
NOCYCLE;


--affiliation_id primary key generator:

-- DROP SEQUENCE AFFILIATION_ID_GENERATOR;

CREATE SEQUENCE AFFILIATION_ID_GENERATOR
INCREMENT BY 1
START WITH 6000
NOCYCLE;


--pub_id primary key generator:

-- DROP SEQUENCE PUB_ID_GENERATOR;

CREATE SEQUENCE PUB_ID_GENERATOR
INCREMENT BY 1
START WITH 1000
NOCYCLE;


--post_id primary key generator:

-- DROP SEQUENCE POST_ID_GENERATOR;

CREATE SEQUENCE POST_ID_GENERATOR
INCREMENT BY 1
START WITH 20100
NOCYCLE;


--doc_id primary key generator:

-- DROP SEQUENCE DOC_ID_GENERATOR;

CREATE SEQUENCE DOC_ID_GENERATOR
INCREMENT BY 1
START WITH 8200
NOCYCLE;


--library_id primary key generator:

-- DROP SEQUENCE LIBRARY_ID_GENERATOR;

CREATE SEQUENCE LIBRARY_ID_GENERATOR
INCREMENT BY 1
START WITH 20200
NOCYCLE;


--alert pk generator sequene for all_sequence:

-- DROP SEQUENCE ALERTS_ID_GENERATOR

CREATE SEQUENCE ALERTS_ID_GENERATOR
INCREMENT BY 1
START WITH 1000
NOCYCLE;