--NOTI ON CITE TRIGGER:


CREATE OR REPLACE TRIGGER NOTI_ON_CITE
AFTER INSERT
ON CITES
FOR EACH ROW
DECLARE
  TEMP_DOC_ID NUMBER;
  TEMP_TIME DATE;
  TEMP_DESCRIPTION VARCHAR2(1000);

  TEMP_CITER_ID NUMBER;
  CITER_TITLE VARCHAR2(500);
  CITER_URL VARCHAR2(800);
  CITER_AUTHORS VARCHAR2(500);
BEGIN
  TEMP_DOC_ID := :NEW.CITEE_ID;
  TEMP_CITER_ID := :NEW.CITER_ID;
  TEMP_TIME := :NEW.CITE_TIME;
	
	CITER_AUTHORS := '';
	FOR AUTHOR IN (
		SELECT (INITCAP(P1.FIRST_NAME) || ' ' || INITCAP(P1.LAST_NAME) ) NAME
		FROM PERSON P1, WRITTEN_BY W1 
		WHERE W1.DOC_ID = TEMP_CITER_ID AND W1.RESEARCHER_ID = P1.PERSON_ID)
	LOOP
		CITER_AUTHORS := CITER_AUTHORS || AUTHOR.NAME || ', ';
	END LOOP;
	
	CITER_AUTHORS := SUBSTR(CITER_AUTHORS, 1, LENGTH(CITER_AUTHORS) - 2);
	
	DBMS_OUTPUT.PUT_LINE(CITER_AUTHORS);
		
	
  FOR R IN (SELECT PER.PERSON_ID FROM WRITTEN_BY WBY, PERSON PER
   		WHERE WBY.DOC_ID = TEMP_DOC_ID AND PER.PERSON_ID = WBY.RESEARCHER_ID)
  LOOP

    SELECT TITLE, URL INTO CITER_TITLE, CITER_URL FROM DOCUMENT WHERE DOC_ID = TEMP_CITER_ID;

    TEMP_DESCRIPTION := 'You got new citation from "' || INITCAP(CITER_TITLE) || '" Authored by ' || CITER_AUTHORS; 

    INSERT INTO NOTIFICATION VALUES(NOTIFICATION_ID_GENERATOR.NEXTVAL, R.PERSON_ID, TEMP_DOC_ID, 'cite', TEMP_TIME, TEMP_DESCRIPTION);
  END LOOP;
 	
END;
/
