-- add eemail, type of person

ALTER TABLE PERSON
ADD (
	email        VARCHAR2(500) UNIQUE,
	is_reseacher NUMBER DEFAULT 0 NOT NULL CHECK (is_reseacher BETWEEN 0 and 1),
	is_user      NUMBER DEFAULT 1 NOT NULL CHECK (is_user BETWEEN 0 and 1)
);

-- is_deleted for recovery
ALTER TABLE USER_
ADD (
	is_deleted NUMBER CHECK (is_deleted BETWEEN 0 and 1)
);

-- publication type
ALTER TABLE PUBLICATION
ADD (
	pub_type VARCHAR2(100)
);
-- add post type
ALTER TABLE POSTS
ADD (
	is_discussion NUMBER CHECK (is_discussion BETWEEN 0 and 1)
);


ALTER TABLE DOCUMENT
ADD (
	is_patent NUMBER CHECK (is_patent BETWEEN 0 and 1),	
);


-- 
CREATE TABLE user_setting (
  user_id               INTEGER,
  
  is_any_lang           INTEGER DEFAULT 1 NOT NULL CHECK (is_any_lang BETWEEN 0 and 1),
  use_search_activity   INTEGER DEFAULT 1 NOT NULL CHECK (use_search_activity BETWEEN 0 and 1),
  include_patents       INTEGER DEFAULT 1 NOT NULL CHECK (include_patents BETWEEN 0 and 1), 
  open_in_new_window    INTEGER DEFAULT 1 NOT NULL CHECK (open_in_new_window BETWEEN 0 and 1),  
  show_citation_link    INTEGER DEFAULT 1 NOT NULL CHECK (show_citation_link BETWEEN 0 and 1),
  
  CONSTRAINT account_setting_pk PRIMARY KEY (user_id),
  CONSTRAINT account_setting_fk FOREIGN KEY(user_id) 
    REFERENCES user_(person_id) ON DELETE CASCADE
);


CREATE TABLE researcher_setting (
  researcher_id INTEGER,
  auto_update   INTEGER DEFAULT 1 NOT NULL CHECK (auto_update BETWEEN 0 and 1),
  is_public     INTEGER DEFAULT 1 NOT NULL CHECK (is_public BETWEEN 0 and 1),

  CONSTRAINT researcher_setting_pk PRIMARY KEY (researcher_id),
  CONSTRAINT researcher_setting_fk FOREIGN KEY(researcher_id) 
    REFERENCES researcher(person_id) ON DELETE CASCADE
);


-- langugage is complicated
CREATE TABLE laguages (
	lang_id         INTEGER,
	english_name    VARCHAR2(100) NOT NULL,
	ISO_639_1_Code  VARCHAR2(100),
	CONSTRAINT laguages_pk PRIMARY KEY(lang_id)
);

-- document is_patent
ALTER TABLE DOCUMENT
ADD (
	lang_id NUMBER,
	CONSTRAINT doc_lang FOREIGN KEY(lang_id) 
    REFERENCES laguages(lang_id) ON DELETE CASCADE
);


CREATE TABLE user_language (
	user_id         INTEGER,
	lang_id         INTEGER,
	
	CONSTRAINT user_language_pk PRIMARY KEY (user_id, lang_id),
	CONSTRAINT user_language_fk FOREIGN KEY(user_id) 
    REFERENCES user_(person_id) ON DELETE CASCADE,
	CONSTRAINT user_language_fk2 FOREIGN KEY(lang_id)
    REFERENCES laguages(lang_id) ON DELETE CASCADE
);

-- add results per page
ALTER TABLE user_setting
ADD (
	results_per_page INTEGER DEFAULT 10 NOT NULL
);

-- add new column for the doc referring to a discussion
ALTER TABLE DISCUSSION
	ADD	doc_id INTEGER DEFAULT 8000 NOT NULL 
		CONSTRAINT discussion_doc_fk REFERENCES DOCUMENT(DOC_ID);


-- add data to discussion table for docs (actually dataset)
DECLARE
i INTEGER := 8000;
BEGIN
	FOR cur IN (SELECT post_id FROM DISCUSSION) LOOP
		dbms_output.put_line(cur.POST_ID);
		UPDATE DISCUSSION dis
			SET doc_id = i
			WHERE dis.POST_ID = cur.POST_ID;
		i := i + 1;
			
	END LOOP;

END;
/


-- NOTI_TYPES ('COMMENT', 'REPLY', 'CITE')
-- PERSON_ID IS WHOSE NOTI IS THIS.
-- DESCRIBE : COMMENTED/REPLIED ON THIS DISCUSSION. /GOT NEW CITATION. SOMETHING LIKE THIS.

--DROP TABLE NOTIFICATION

CREATE TABLE NOTIFICATION(
	
	NOTI_ID NUMBER,
	PERSON_ID NUMBER,
	DOC_ID NUMBER,
	NOTI_TYPE VARCHAR2(500),
	EVENT_TIME DATE DEFAULT SYSDATE,
	DESCRIPTION VARCHAR2(500),
	
	CONSTRAINT NOTIFICATION_PK PRIMARY KEY(NOTI_ID),
	CONSTRAINT NOTIFICATION_FK1 FOREIGN KEY(PERSON_ID) REFERENCES PERSON ON DELETE CASCADE,
	CONSTRAINT NOTIFICATION_FK2 FOREIGN KEY(DOC_ID) REFERENCES DOCUMENT ON DELETE CASCADE
	
);

CREATE GLOBAL TEMPORARY TABLE TEMP_WRITTEN_BY(
	RESEARCHER_ID NUMBER, 
	DOC_ID NUMBER
	) ON COMMIT PRESERVE ROWS;
	
	
ALTER TABLE CITES
ADD (
	CITE_TIME DATE DEFAULT SYSDATE
);

ALTER TABLE PERSON 
ADD(
	IS_ADMIN NUMBER DEFAULT 0,
	IS_AUTO_GENERATED NUMBER DEFAULT 0
);

-- rename to fix typo
ALTER TABLE PERSON
RENAME COLUMN IS_RESEACHER
TO IS_RESEARCHER;


--CREATING ALERTS_PENDING TABLE 

-- DROP TABLE ALERTS_PENDING;

CREATE TABLE ALERTS_PENDING (
ALERTS_PENDING_ID INTEGER,
ALERT_ID INTEGER NOT NULL,
DOC_ID NUMBER NOT NULL,
AUTHORS_LIST VARCHAR2(500),

CONSTRAINT ALERTS_PENDING_PK PRIMARY KEY(ALERTS_PENDING_ID),
CONSTRAINT ALERTS_PENDING_FK FOREIGN KEY(ALERT_ID) REFERENCES ALERTS ON DELETE CASCADE,
CONSTRAINT ALERTS_PENDING_FK2 FOREIGN KEY(DOC_ID) REFERENCES DOCUMENT ON DELETE CASCADE
);


-- add gscholar columns
ALTER TABLE RESEARCHER 
ADD(
	homepage VARCHAR2(500),
	interests VARCHAR2(500)
);





