# Generated by Django 3.1.1 on 2020-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
